services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: user
      MYSQL_PASSWORD:
    ports:
      - '3306:3306'
    volumes:
      - ./docker/dbdata:/var/lib/mysql
